# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-21 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ba_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='Notes has been added'),
            preserve_default=False,
        ),
    ]
