# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-21 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='description',
            field=models.TextField(default='This is coooooooollllll!!!!!!!!!!'),
            preserve_default=False,
        ),
    ]
