# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='fisrt_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='First Name', max_length=45),
            preserve_default=False,
        ),
    ]
