# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='users',
            field=models.ManyToManyField(related_name='manytomany', to='exam_app.User'),
        ),
    ]
