# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_quotes_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotes',
            new_name='Quote_page',
        ),
    ]
