# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0006_auto_20190222_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=45)),
                ('quote', models.CharField(max_length=45)),
                ('users', models.ManyToManyField(related_name='manytomany', to='exam_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='quote_page',
            name='users',
        ),
        migrations.DeleteModel(
            name='Quote_page',
        ),
    ]
