# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_auto_20190222_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='author',
            field=models.CharField(default='author', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='quote',
            field=models.CharField(default='quote', max_length=45),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
