# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0008_auto_20190222_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.IntegerField(default='0', max_length=5),
            preserve_default=False,
        ),
    ]
