# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0009_user_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=45)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='exam_app.User'),
        ),
    ]
