# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-22 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0010_auto_20190222_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like',
        ),
    ]
